### PR TITLE
Improving audio support and udpating to latest Node LTS version

### PR DESCRIPTION
**Pull request by mga-97**
- Added missing methods for the Sound class.
- Removed some problematic hard coding.
- Fixed stream_audio example, before it was streaming with the incorrect sample rate and length.
- Updated and tested to work with Node version 20.14.0.

### CODE REVIEW

**Comment by traversaro** [comment]
Hello @mga-97 ! At the moment not a lot of people are working on the repo, do you want to discuss about this tomorrow (if you are at IIT?), thanks!

**Comment by mga-97** [comment]
Hi, yes that would be good, I am at CRIS today and tomorrow and should be free pretty much anytime, let me know what works for you.

**Review by traversaro — APPROVED** [review]

**Comment by randaz81** [comment]
@traversaro Can we make another release now that we are compatible with Node.js 20.14.0?

**Comment by traversaro** [comment]
Sure, as I explained to @mga-97 and @elandini84 no one is currently using the repo on the AMI side, so feel free to do any tag/release as you prefer (I gave full access to @mga-97 and @elandini84 to do so).

**Pull request merged**
