### PR TITLE
Leave to YARP the pixel code (channel order) conversion aligned with OpenCV (BGRx)

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #43 .

### CODE REVIEW

**Comment by nunoguedelha** [comment]
This is a first attempt to use `yarp::sig::toCvMat` function for converting the pixel code for aligning it with the default channel order used by OpenCV.

There is a problem with the definition of the map `yarpCode2toCvMat`: for adding another line with a different pixel code (e.g. `yarp::sig::PixelMono`), I would need to have a generic type `x` in the declaration of the map, which accepts both `yarp::sig::PixelMono` and `yarp::sig::PixelRgb` (like a "union"). Same applies to all the other lines in `yarpCode2toCvMat` still commented. Using a parent class of `ImageOf`, i.e. `Image` doesn't seem to work.

**Comment by nunoguedelha** [comment]
CC @S-Dafarra @riccardogrieco

**Comment by nunoguedelha** [comment]
> There is a problem with the definition of the map `yarpCode2toCvMat`: for adding another line with a different pixel code (e.g. `yarp::sig::PixelMono`), I would need to have a generic type `x` in the declaration of the map, which accepts both `yarp::sig::PixelMono` and `yarp::sig::PixelRgb` (like a "union"). Same applies to all the other lines in `yarpCode2toCvMat` still commented. Using a parent class of `ImageOf`, i.e. `Image` doesn't seem to work.

This problem was avoided. Refer to #43 .

**Review by traversaro — APPROVED** [review]
Cool!

**Comment by nunoguedelha** [comment]
Side note:
I selected "Squash and merge" but it kept the old commits and created a new merge commit, just as if I had chosen "Create new merge commit".
CC @traversaro

**Pull request merged**
