### PR TITLE
Fix includes and define IMWRITE_PNG_COMPRESSION and IMWRITE_JPEG_QUALITY in cv:: namespace

### PR DESCRIPTION
**Pull request by nunoguedelha**
Fixes https://github.com/robotology/yarp.js/issues/17 .

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @Nicogene @vtikha

**Comment by traversaro** [comment]
I think probably the fix is related to a recent OpenCV rather then a recent YARP, but it any case it probably make sense to merge it.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@cciliber we are finally starting using yarp.js as I promised years ago :D

**Comment by nunoguedelha** [comment]
Thanks @traversaro

**Pull request merged**
