### PR TITLE
Connect Yarp port /icubSim/inertial to Yarp.JS and OpenMCT plotting

### PR DESCRIPTION
**Pull request by nunoguedelha**
This PR implements the integration of a telemetry server on YarpJS for serving Open MCT telemetry visualizer.

We connect the robot interface Yarp ports to the Open MCT via the `yarp.js` Yarp-to-websocket server are listed below as follows:
- [x] Retrieve Yarp data: the `yarp.js` server reads the Yarp output ports, like for instance `/icubSim/inertial`. => DONE (server created and working on http or https.)
- [x] History and Realtime servers (listen to OpenMCT): for extending the server with these services, `yarp.js` has two additional sockets `http://localhost:<port>/history` and `http://localhost:<port>/realtime` where it listens to requests coming from OpenMCT, asking for new telemetry data. => DONE
- [x] History and Realtime servers (reply to OpenMCT):`yarp.js` replies sending the buffered data within a range depending on the requested time boundaries. => DONE
    - [x] Realtime data request by Open MCT was failing. => This was due to wrong request address from the Realtime Telemetry plugin (in Open MCT) => now set to ws://localhost:<yarp.js port>/realtime (https://github.com/dic-iit/element_software-engineering/issues/50#issuecomment-863877317 and https://github.com/dic-iit/element_software-engineering/issues/50#issuecomment-864163884)
    - [x] "Cross-Origin Request Blocked" issue. => Open MCT server configuration has the "Same Origin resource" constraint when fetching data from resources. => solved by properly setting the CORS settings in the response header from the Yarp.js server (https://github.com/dic-iit/element_software-engineering/issues/50#issuecomment-864163884 and https://github.com/dic-iit/element_software-engineering/issues/50#issuecomment-864724209)
- [x] Bufferize data: the data read from the YARP port should then be pushed to the History server buffer. Scalar and vector data should be supported. => DONE (https://github.com/dic-iit/element_software-engineering/issues/50#issuecomment-865529850)
- [x] Limit History server buffer depth. => DONE

### CODE REVIEW

**Comment by nunoguedelha** [comment]
Ciao @traversaro , I couldn't move https://github.com/dic-iit/element_software-engineering/issues/50 to this repo using "Move issue", neither with "Transfer issue". I still have no idea why it works for some repos and not others.

**Comment by traversaro** [comment]
Hi @nunoguedelha ! All this `openmct` related material is great, but I wonder if the `yarp.js` repo is the best place were to host it? Perhaps we can create a `yarp-openmct` repo, and add it there, so that we can continue to use that repo as an entrypoint for YARP-OpenMCT integration in general, even if in the future perhaps the integration will not use `yarp.js` at all?

**Comment by nunoguedelha** [comment]
Hi @traversaro , it makes sense. This means creating a repo with typically all the new files from `.../yarp.js/iCubTelemetryVisualizerServer/` and YarpJS module as a dependency. I can do that. Where do we create the repo, `robotology`?

**Comment by traversaro** [comment]
> 
> 
> Hi @traversaro , it makes sense. This means creating a repo with typically all the new files from `.../yarp.js/iCubTelemetryVisualizerServer/` and YarpJS module as a dependency. I can do that. Where do we create the repo, `robotology`?

I created it in https://github.com/dic-iit/yarp-openmct, you have full admin access.

**Comment by nunoguedelha** [comment]
Thanks @traversaro !

As soon as I move the code there and open a PR, I'll close this one.

**Comment by nunoguedelha** [comment]
PR changes moved to https://github.com/dic-iit/yarp-openmct/pull/1.

**Pull request closed without merging**
